name: event_source
version: 0.0.2
author: Zdeslav Vojkovic <zdeslav.vojkovic@gmail.com>
description: Wrist friendly events for Dart
homepage: https://github.com/zdeslav/event_source
documentation: https://github.com/zdeslav/event_source
environment:
  sdk: '>=0.5.0'
dev_dependencies:
  unittest: '>=0.5.0'
